### ISSUE TITLE
A website version and invitation

### ISSUE THREAD

**Issue by FunnySaltyFish** [SunLemuria/OpenGPTAndBeyond#1]
Hello, thanks for your hard work. I write a simple website [llm.best](https://llm.best) based on your list, and is collecting and improving the list(both open-source and closed ones). The website is open source as well, you can visit its code [here](https://github.com/FunnySaltyFish/best_llm). May I invite you to help collect and maintain the website version together? I believe a web and `json` are easier to spread and use for the public.

**Comment by SunLemuria** [comment]
First of all, thank you for your attention and the effort to write the website!
but I don't think I'll have the enough time to do this work, because the models are emerging more and more quickly, and I think my repo, besides adding more models, will adjust over time, like partitioning into several sections few days ago, and maybe this will cause a refactoring in your code?
I think more people should get involved to do this work.

**Comment by FunnySaltyFish** [comment]
> I think more people should get involved to do this work.  

I cannot agree it more. I believe it is the community that can maintain such a huge project. And that's why I created this issue.

> I don't think I'll have the enough time to do this work

I think you've done so well. Your list is updated over time just by yourself, that's astonishing. From my idea, if you accept to join the website, what you need to do is just maintaining the [llms.json](https://github.com/FunnySaltyFish/best_llm/blob/master/llms.json), maybe as same as maintaining the README here.

> like partitioning into several sections few days ago, and maybe this will cause a refactoring in your code?

For each llm, there is a `tags` field, which is an array including some "features" of that llm. Maybe that can be used to represent the "section" here. In that case, filtering the llms by tags might be necessary to be added to the website. 

唉，实话说我也不是很擅长网页开发，我也试着能不能四处找找，看有没有志同道合的人一起参与进来。

**Comment by SunLemuria** [comment]
机器之心搞了个列表：[https://sota.jiqizhixin.com/models/list](https://sota.jiqizhixin.com/models/list)，他们团队收的可能更全一点 ...
所以我想我这个仓库就作为个人兴趣来弄，您的网页版您看要不要继续维护下去呢，如果要维护下去，我就加到我的readme里来，看有没有同学一起来优化

**Comment by FunnySaltyFish** [comment]
有心无力啊，我看了看那个网站，最早上溯到2020年了，180页，这是个人永远无法来完成的……您也不用写到README里了，我闲余时推动它试试，不行就算了。也祝你的这个列表越做越好~

**Comment by SunLemuria** [comment]
我先加进来，有啥变化后面再说

**Comment by SunLemuria** [comment]
加进来了：[这个commit](https://github.com/SunLemuria/open_source_chatgpt_list/commit/5240842f72f40cba6e866ba47c7564454af8c2b7)

**Comment by FunnySaltyFish** [comment]
好的，谢谢！
